Predelani datumu do ANSI
jakubboucek/martinova-skolka pull request #1
Opened 2018-12-05 17:48 UTC by Dosty85

2018-12-05 18:02 UTC, jakubboucek commented
Když kód spustím u sebe, tak generuje odlišný výstup… :-(

![image](https://user-images.githubusercontent.com/1657322/49533793-3b791380-f8c0-11e8-9a3a-ba6d971cfafc.png)

2018-12-05 18:03 UTC, jakubboucek requested changes
Když kód spustím u sebe, tak generuje odlišný výstup… :-(

![image](https://user-images.githubusercontent.com/1657322/49533793-3b791380-f8c0-11e8-9a3a-ba6d971cfafc.png)

2020-10-18 19:56 UTC, jakubboucek commented
Po dvou letech zavírám, asi se to nebude nikdy dotahovat.

2020-10-18 19:56 UTC, closed without merging

2020-10-23 06:12 UTC, Dosty85 commented
Hmm... spíš to znovu otevřu. Najdu si na to čas. Chtěl bych to dokončit :)